blank_issues_enabled: true
contact_links:
  - name: Сообщить о уязвимости
    url: https://github.com/nekotyy/misis-rasp-bot/security/advisories
    about: Пожалуйста, отправляйте сообщения об уязвимостях сюда.
